const regForName = /^[а-яёa-z]+(?:[-]{1}[а-яёa-z]*)?$/i;
const reqForEmail = /^([A-Za-z0-9_\-.])+@([A-Za-z0-9_\-.])+\.([A-Za-z]{2,4})$/;

const TABLETRESIZE = 1096;
const MOBILERESIZE = 684;
const DEFAULTNUMBERSOFCARDSFULL = 12;
const DEFAULTNUMBERSOFCARDSTABLET = 8;
const DEFAULTNUMBERSOFCARDSMOBILE = 5;
const DEFAULTNUMBERSOFCARDSTOADDFULL = 3;
const DEFAULTNUMBERSOFCARDSTOADDTABLET = 2;
const DEFAULTNUMBERSOFCARDSTOADDMOBILE = 5;

export {
  regForName,
  reqForEmail,
  TABLETRESIZE,
  MOBILERESIZE,
  DEFAULTNUMBERSOFCARDSFULL,
  DEFAULTNUMBERSOFCARDSTABLET,
  DEFAULTNUMBERSOFCARDSMOBILE,
  DEFAULTNUMBERSOFCARDSTOADDFULL,
  DEFAULTNUMBERSOFCARDSTOADDTABLET,
  DEFAULTNUMBERSOFCARDSTOADDMOBILE,
};