const regForName = /^[а-яёa-z]+(?:[-]{1}[а-яёa-z]*)?$/i;
const reqForEmail = /^([A-Za-z0-9_\-.])+@([A-Za-z0-9_\-.])+\.([A-Za-z]{2,4})$/;

const TABLET_RESIZE = 1096;
const MOBILE_RESIZE = 684;
const DEFAULT_NUMBERS_OF_CARDS_FULL = 12;
const DEFAULT_NUMBERS_OF_CARDS_TABLET = 8;
const DEFAULT_NUMBERS_OF_CARDS_MOBILE = 5;
const DEFAULT_NUMBERS_OF_CARDS_TO_ADD_FULL = 3;
const DEFAULT_NUMBERS_OF_CARDS_TO_ADD_TABLET = 2;
const DEFAULT_NUMBERS_OF_CARDS_TO_ADD_MOBILE = 5;

export {
  regForName,
  reqForEmail,
  TABLET_RESIZE,
  MOBILE_RESIZE,
  DEFAULT_NUMBERS_OF_CARDS_FULL,
  DEFAULT_NUMBERS_OF_CARDS_TABLET,
  DEFAULT_NUMBERS_OF_CARDS_MOBILE,
  DEFAULT_NUMBERS_OF_CARDS_TO_ADD_FULL,
  DEFAULT_NUMBERS_OF_CARDS_TO_ADD_TABLET,
  DEFAULT_NUMBERS_OF_CARDS_TO_ADD_MOBILE,
};